name: "Build and Release"

on: 
  push: 
    branches: 
      - master

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17.0.10
        uses: actions/setup-java@v1
        with: 
          java-version: '17.0.10'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with: 
          flutter-version: '3.22.2'
    
      - name: Decode and setup keystore
        env:
            ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
            echo $ANDROID_KEYSTORE_BASE64 | base64 --decode > $HOME/releasekey.jks
            mkdir -p $GITHUB_WORKSPACE/android/app
            mv $HOME/releasekey.jks $GITHUB_WORKSPACE/android/app/releasekey.jks

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with: 
          name: myBmi
          path: build/app/outputs/flutter-apk/app-release.apk

                